import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Workbench } from "@deepdish/workbench";
import { configure } from "@deepdish/ui/config";
import { cloudConfig } from "@deepdish-cloud/config";
import { init } from "@deepdish-cloud/config/client";

configure(
	cloudConfig({
		secretKey: process.env.DEEPDISH_SECRET_KEY,
		projectAlias: process.env.DEEPDISH_PROJECT_ALIAS,
	}),
);

const showWorkbench = process.env.DEEPDISH_MODE === "draft";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});

const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{children}
				{showWorkbench && <Workbench onInit={init} />}
			</body>
		</html>
	);
}
